/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewGameRouteImport } from './routes/new-game'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'
import { Route as LocaleNewGameRouteImport } from './routes/$locale.new-game'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'
import { Route as LocaleGameGameIdRouteImport } from './routes/$locale.game.$gameId'

const NewGameRoute = NewGameRouteImport.update({
  id: '/new-game',
  path: '/new-game',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleNewGameRoute = LocaleNewGameRouteImport.update({
  id: '/new-game',
  path: '/new-game',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGameGameIdRoute = LocaleGameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/new-game': typeof NewGameRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/new-game': typeof LocaleNewGameRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/game/$gameId': typeof LocaleGameGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/new-game': typeof NewGameRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/new-game': typeof LocaleNewGameRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/game/$gameId': typeof LocaleGameGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/new-game': typeof NewGameRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/new-game': typeof LocaleNewGameRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/game/$gameId': typeof LocaleGameGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/new-game'
    | '/$locale/about'
    | '/$locale/new-game'
    | '/game/$gameId'
    | '/$locale/'
    | '/$locale/game/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/new-game'
    | '/$locale/about'
    | '/$locale/new-game'
    | '/game/$gameId'
    | '/$locale'
    | '/$locale/game/$gameId'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/about'
    | '/new-game'
    | '/$locale/about'
    | '/$locale/new-game'
    | '/game/$gameId'
    | '/$locale/'
    | '/$locale/game/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AboutRoute: typeof AboutRoute
  NewGameRoute: typeof NewGameRoute
  GameGameIdRoute: typeof GameGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-game': {
      id: '/new-game'
      path: '/new-game'
      fullPath: '/new-game'
      preLoaderRoute: typeof NewGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/new-game': {
      id: '/$locale/new-game'
      path: '/new-game'
      fullPath: '/$locale/new-game'
      preLoaderRoute: typeof LocaleNewGameRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/game/$gameId': {
      id: '/$locale/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/$locale/game/$gameId'
      preLoaderRoute: typeof LocaleGameGameIdRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleNewGameRoute: typeof LocaleNewGameRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleGameGameIdRoute: typeof LocaleGameGameIdRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleNewGameRoute: LocaleNewGameRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleGameGameIdRoute: LocaleGameGameIdRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AboutRoute: AboutRoute,
  NewGameRoute: NewGameRoute,
  GameGameIdRoute: GameGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
